"""Add sku category and mixed sales

Revision ID: e4a227be4a08
Revises: 2947f2daf095
Create Date: 2026-02-17 08:48:59.820662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a227be4a08'
down_revision = '2947f2daf095'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('image', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_unique_constraint(None, 'products', ['id'])
    op.add_column('transaction_items', sa.Column('sale_type', sa.Enum('WHOLESALE', 'RETAIL', 'MIXED', name='saletype'), nullable=False))
    op.create_unique_constraint(None, 'transaction_items', ['id'])
    op.create_unique_constraint(None, 'transactions', ['id'])
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'full_name')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint(None, 'transaction_items', type_='unique')
    op.drop_column('transaction_items', 'sale_type')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_column('products', 'image')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'category')
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###
